#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=0
#SBATCH --time=03:00:00
#SBATCH --partition=fge
#SBATCH --qos=gpu
#SBATCH --account=rda-ghpcs
#SBATCH --mail-type=ALL
#SBATCH --mail-user="annabel.wade@noaa.gov"
#SBATCH --chdir=.

unset SLURM_MEM_PER_NODE
unset SLURM_MEM_PER_GPU

module purge
module load cuda

source /scratch1/RDARCH/rda-ghpcs/Annabel.Wade/miniconda3/etc/profile.d/conda.sh
conda activate smoke

python test_model.py 1 True /scratch1/RDARCH/rda-ghpcs/Rey.Koki/SmokeViz_code/deep_learning/dataset_pointers/pseudo/pseudo.pkl
exit 0
